apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-portfolio-pvc

spec:
  storageClassName: "my-portfolio-storage-class"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi